spring:
  application:
    name: TwitterToKafkaService

twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservice
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Hello Kafka!
  enable-v1-tweets: false
  enable-v2-tweets: false
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansion=author_id
  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: ${TWITTER_BEARER_TOKEN}
